### PR TITLE
Add JAR plugin for easy installation

### LINKED ISSUE #178: Add a JAR
This is a tracking issue for my efforts to package the build distributable as a JAR
You all have my leave to harangue, bother and ping me if/when I don't get back to this!

### PR DESCRIPTION
**Pull request by SNDST00M**
Closes #178.
Should automate the copying process I hope.
Most users are so-called "script kiddies" and need a guide just to install this.
JAR package process is as simple as `cd java && mvn package & cd ..` in command line.

### CODE REVIEW

**Comment by SNDST00M** [comment]
A version bump to 2.0.0-beta-5 is necessary once this ships. Would a Maven test job be welcome in the CI?

**Comment by JLyne** [comment]
Interesting idea, didn't think about using a plugin for installation. Will take a proper look at this when I get the time.

**Comment by SNDST00M** [comment]
Is there an option to not hash the files? I need to copy them manually with `Plugin#saveResource` but they are all hashed which is making the job a little tougher.

**Comment by SNDST00M** [comment]
Update - I found a way to extract them off the JAR directly :) very hyped for this!

**Comment by SNDST00M** [comment]
Ready for QA and ship!

**Comment by SNDST00M** [comment]
Theres a lot of merge commit noise I notice, and I do recommend that this pull blocks the others to prevent more!

**Comment by JLyne** [comment]
Appreciate the work on this. Will setup an action for it.

**Pull request merged**
